/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/html/index.html"],
  safelist: [
    "text-[6rem]",
    "text-dark",
    "mb-4",
    "mt-5",
    "text-lg",
    "border-[2px]",
    "border-dotted",
    "border-accent",
    "text-accent",
    "rounded",
    "hover:bg-accent",
    "hover:text-dark",
    "transition",
    ".overflow-hidden",
    ".shadow-xl",
    ".rounded-xl",
    ".w-[300px]",
    ".h-[200px]",
    ".p-3",
    ".text-lg",
    ".font-bold",
    ".text-sm",
    ".opacity-80",
    ".flex",
    ".justify-end",
    ".p-2",
    "hover:border-dotted",
    "hover:border-[2px]",
    "rounded",
    "bg-accent",
    "text-dark",
    "hover:border-dark",
    "hover:bg-primary",
    "hover:text-dark",
    "min-w-[300px]",
    "h-3/4",
    "object-cover",
    "flex-col",
    "justify-end",
    "flex-1",
    "align-bottom",
  ],
  theme: {
    colors: {
      accent: "#6ac15c",
      secondary: "#F9A826",
      primary: "#EFF1D3",
      dark: "#171717",
    },
    extend: {
      fontFamily: {
        handWritten: ["Handlee", "serif"],
      },
    },
  },
  plugins: [],
};
